import type { CheckReport, FileResult } from '../metrics/schema.ts';
import { RENDER_VIEWS } from '../render/types.ts';

export const STICKY_MARKER = '<!-- cadgate:report:v1 -->';

export interface ImageResolver {
  /** Maps an absolute PNG path to a public URL (orphan branch raw URL or data URI). */
  (absPath: string): string;
}

export function renderMarkdown(report: CheckReport, resolveImage: ImageResolver): string {
  const lines: string[] = [];
  const headline = headlineFor(report);
  lines.push(STICKY_MARKER);
  lines.push(`## CADGate ${headline}`);
  lines.push('');
  lines.push(`**${report.base}…${report.head}** • ${report.summary.filesChanged} file${report.summary.filesChanged === 1 ? '' : 's'}`);
  lines.push('');
  lines.push(summaryTable(report));
  lines.push('');
  for (const file of report.files) {
    if (file.status !== 'analyzed') continue;
    lines.push(...renderFileSection(file, resolveImage));
  }
  lines.push('');
  lines.push('<sub>generated by [cadgate](https://github.com/vericontext/cadgate)</sub>');
  return lines.join('\n');
}

function headlineFor(report: CheckReport): string {
  const { filesFailed, filesWithViolations } = report.summary;
  if (filesWithViolations > 0) return `❌ ${filesWithViolations} violation${filesWithViolations === 1 ? '' : 's'}`;
  if (filesFailed > 0) return `❌ ${filesFailed} file${filesFailed === 1 ? '' : 's'} failed`;
  return '✅ all checks passed';
}

function summaryTable(report: CheckReport): string {
  const rows: string[] = [];
  rows.push('| file | language | min wall | Δvolume | watertight | violations |');
  rows.push('|------|----------|----------|---------|------------|------------|');
  for (const file of report.files) {
    if (file.status !== 'analyzed') {
      rows.push(`| \`${file.path}\` | — | — | — | — | skipped |`);
      continue;
    }
    const head = file.head;
    const headOk = head.state === 'ok' ? head : null;
    const minWall = headOk ? formatMinWall(headOk.metrics.minWallMm) : '—';
    const delta = file.delta.kind === 'changed' ? formatPct(file.delta.volumeDeltaPct) : kindLabel(file.delta);
    const watertight = headOk ? (headOk.metrics.isWatertight ? '✅' : '❌') : '—';
    const errors = file.dfmViolations.filter((v) => v.severity === 'error').length;
    const warns = file.dfmViolations.filter((v) => v.severity === 'warn').length;
    const violationCell =
      errors === 0 && warns === 0
        ? '✅'
        : `${errors > 0 ? `${errors} ❌` : ''}${errors > 0 && warns > 0 ? ' / ' : ''}${warns > 0 ? `${warns} ⚠️` : ''}`;
    rows.push(`| \`${file.path}\` | ${file.language} | ${minWall} | ${delta} | ${watertight} | ${violationCell} |`);
  }
  return rows.join('\n');
}

function renderFileSection(file: FileResult & { status: 'analyzed' }, resolveImage: ImageResolver): string[] {
  const out: string[] = [];
  out.push(`### \`${file.path}\``);
  if (file.head.state === 'ok' && file.head.renders) {
    const r = file.head.renders;
    out.push('');
    out.push(`| ${RENDER_VIEWS.map((v) => capitalize(v)).join(' | ')} |`);
    out.push(`| ${RENDER_VIEWS.map(() => ':-:').join(' | ')} |`);
    out.push(`| ${RENDER_VIEWS.map((v) => `<img width="180" src="${resolveImage(r[v])}">`).join(' | ')} |`);
  }
  if (file.dfmViolations.length > 0) {
    out.push('');
    out.push('**DFM Violations**');
    for (const v of file.dfmViolations) {
      const icon = v.severity === 'error' ? '❌' : '⚠️';
      out.push(`- ${icon} \`${v.ruleId}\` — ${v.message}`);
    }
  }
  if (file.head.state === 'ok' && file.head.metrics.minWallHotspots.length > 0) {
    out.push('');
    out.push(`<details><summary>Min-wall hotspots (${file.head.metrics.minWallHotspots.length})</summary>`);
    out.push('');
    for (const h of file.head.metrics.minWallHotspots) {
      out.push(`- \`(${h.point.map((n) => n.toFixed(2)).join(', ')})\` — ${h.thicknessMm.toFixed(2)} mm`);
    }
    out.push('');
    out.push('</details>');
  }
  out.push('');
  return out;
}

function formatMinWall(mm: number): string {
  if (mm < 0) return '—';
  return mm < 1.0 ? `**${mm.toFixed(2)} mm** ❌` : `${mm.toFixed(2)} mm`;
}

function formatPct(pct: number): string {
  const sign = pct >= 0 ? '+' : '';
  const flag = Math.abs(pct) > 5 ? ' ⚠️' : '';
  return `${sign}${pct.toFixed(1)} %${flag}`;
}

function kindLabel(delta: { kind: string }): string {
  return delta.kind;
}

function capitalize(s: string): string {
  return s[0]!.toUpperCase() + s.slice(1);
}
